name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Compose
      run: sudo apt-get install docker-compose

    - name: Docker Compose up
      run: docker-compose up -d

    - name: Run health check
      run: |
        # Replace this with your actual health check commands
        sleep 30
        curl -f http://localhost || exit 1

    - name: Create admin user
      run: |
        docker-compose exec panel php artisan p:user:make --email=admin@gmail.com --username=Admin123 --name="Admin User" --password=SecurePass123 --admin

    - name: Docker Compose down
      if: always()
      run: docker-compose down
