name: Deploy Pterodactyl

on:
  push:
    branches:
      - main  # Atur sesuai dengan cabang yang ingin Anda gunakan

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build and run Docker Compose
      run: |
        # Set up Docker Compose
        sudo apt-get update
        sudo apt-get install -y docker-compose

        # Create a directory for Docker Compose configuration
        mkdir -p $HOME/compose
        cp docker-compose.yml $HOME/compose/
        cd $HOME/compose

        # Define environment variables for Docker Compose
        echo "MYSQL_PASSWORD=12345" >> .env
        echo "MYSQL_ROOT_PASSWORD=12345" >> .env
        echo "APP_URL=https://pterodactyl.zall.com" >> .env
        echo "APP_SERVICE_AUTHOR=zall@gmail.com" >> .env
        echo "MAIL_FROM=zall@gmail.com" >> .env
        echo "MAIL_PASSWORD=12345" >> .env

        # Start Docker Compose with the environment variables
        docker-compose up -d

        # Create the user with --no-password flag to avoid interactive input
        docker-compose run --rm panel php artisan p:user:make --email="zall@gmail.com" --username="admin" --name-first="Admin" --name-last="User" --admin=1 --no-password

    - name: Bypass Proxy
      run: |
        export no_proxy="pterodactyl.zall.com"
        
    - name: Keep the job running
      run: |
        echo "Keeping the job running until GitHub Actions time limit..."
        while sleep 60; do :; done
