name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Compose
      run: sudo apt-get install docker-compose

    - name: Docker Compose up
      run: docker-compose up -d

    - name: Create .env file for panel
      run: |
        echo "DB_PASSWORD=CHANGE_ME" >> .env
        echo "APP_URL=https://pterodactyl.zall.com" >> .env
        echo "APP_TIMEZONE=UTC" >> .env
        echo "APP_SERVICE_AUTHOR=noreply@gmail.com" >> .env
        echo "TRUSTED_PROXIES=*" >> .env
        echo "MAIL_FROM=noreply@gmail.com" >> .env
        echo "MAIL_DRIVER=smtp" >> .env
        echo "MAIL_HOST=mail" >> .env
        echo "MAIL_PORT=1025" >> .env
        echo "MAIL_USERNAME=" >> .env
        echo "MAIL_PASSWORD=" >> .env
        echo "MAIL_ENCRYPTION=true" >> .env

    - name: Copy .env file to panel service
      run: docker cp .env $(docker-compose ps -q panel):/app/.env

    - name: Generate application key
      run: docker-compose exec -T panel php artisan key:generate

    - name: Run panel migrations
      run: docker-compose exec -T panel php artisan migrate --force

    - name: Create admin user
      run: |
        docker-compose exec -T panel php artisan p:user:make --email=admin@gmail.com --username=Admin123 --name="Admin User" --password=SecurePass123 --admin
